### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by qhdwns123** [reflare/afl-monitor#2]
Does the script work?

I can not confirm the status.

command: afl-fuzz -i in/ -o out/ -- ./test @@
./afl-monitor -c out/

afl-monitor Version 1.0

[ SUMMARY ]
Fuzzers (Alive/Total):	0 / 0
Total Executions:	0
Current Speed:		0.00 execs/second
Current Speed:		0.00 execs/second
Paths Found (Favs/All):	0 / 0
Pending (Favs/All):	0 / 0
Most Stable Fuzzer:	0.00%
Least Stable Fuzzer:	100.00%
Maximum Cycle Complete:	0
Last Path:		/ ago
Last Hang:		/ ago
Last Crash:		/ ago
Unique Crashes:		0

**Comment by reflare** [comment]
afl-monitor only works for parallel fuzzing jobs (using several AFL instances at once). If you run a single AFL instance, the built in interface is sufficient.
